[package]
name = "git_switch"
version = "0.1.0"
edition = "2024"

[dependencies]
shellexpand = "3.1"

# CLI argument parsing
clap = { version = "4", features = ["derive"] }

# JSON storage for Git accounts
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Error handling
thiserror = "1"

# Async support (optional)
tokio = { version = "1", features = [
    "process",
    "fs",
    "macros",
    "rt-multi-thread",
] }
